mptcp: fix compilation error without MPTCP
Fixing this error:

  In file included from net/core/sock.c:138:
  net/mptcp.h:258:38: error: 'MPTCP_SCHED_NAME_MAX' undeclared here (not in a function); did you mean 'MPTCP_PM_NAME_MAX'?
    258 |         char                    name[MPTCP_SCHED_NAME_MAX];
        |                                      ^~~~~~~~~~~~~~~~~~~~
        |                                      MPTCP_PM_NAME_MAX
  make[3]: *** [scripts/Makefile.build:262: net/core/sock.o] Error 1

Instead of duplicating the define, it is probably better to define it
once even if MPTCP is not set.

Fixes: 0418112ef2da ("mptcp: Cleanup")
Reviewed-by: Christoph Paasch <cpaasch@apple.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
(cherry picked from commit 289570865f4e1bff49407424a541497d3766f1c9)
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>